name: main

on: [push, workflow_dispatch]

jobs:
  test:
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Install Dependencies
        run: flutter pub get
      - name: Run Unit Tests
        run: flutter test